version: '3.8'

# Master Compose File - Starts ALL Services (Core + Monitoring)
# Usage: docker-compose -f ops/compose/docker-compose.full.yml --env-file .env up -d --build

services:
  # Include all core services
  traefik:
    extends:
      file: docker-compose.yml
      service: traefik

  gateway:
    extends:
      file: docker-compose.yml
      service: gateway

  adapter:
    extends:
      file: docker-compose.yml
      service: adapter

  llm-patch:
    extends:
      file: docker-compose.yml
      service: llm-patch

  orchestrator:
    extends:
      file: docker-compose.yml
      service: orchestrator

  ngrok:
    extends:
      file: docker-compose.yml
      service: ngrok

  azurite:
    extends:
      file: docker-compose.yml
      service: azurite

  health-monitor:
    extends:
      file: docker-compose.yml
      service: health-monitor

  # Include all monitoring services
  prometheus:
    extends:
      file: ../monitoring/docker-compose.monitoring.yml
      service: prometheus
    networks:
      - agent-network

  grafana:
    extends:
      file: ../monitoring/docker-compose.monitoring.yml
      service: grafana
    networks:
      - agent-network

  alertmanager:
    extends:
      file: ../monitoring/docker-compose.monitoring.yml
      service: alertmanager
    networks:
      - agent-network

  node-exporter:
    extends:
      file: ../monitoring/docker-compose.monitoring.yml
      service: node-exporter
    networks:
      - agent-network

  cadvisor:
    extends:
      file: ../monitoring/docker-compose.monitoring.yml
      service: cadvisor
    networks:
      - agent-network

  loki:
    extends:
      file: ../monitoring/docker-compose.monitoring.yml
      service: loki
    networks:
      - agent-network

  promtail:
    extends:
      file: ../monitoring/docker-compose.monitoring.yml
      service: promtail
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  azurite-data:
  traefik-data:
  local-llm-models:
  supabase-db-data:
  prometheus-data:
  grafana-data:
  alertmanager-data:
  loki-data:
