services:
  # Simple Gateway für lokale Entwicklung
  gateway-simple:
    image: node:20-alpine
    container_name: code-agent-gateway-simple
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3001
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-test-secret}
    volumes:
      - ../../services/gateway-simple:/app
    working_dir: /app
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Starting simple gateway...' &&
        npm run dev
      "
    networks:
      - code-agent
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Traefik Reverse Proxy
  traefik:
    image: traefik:v3.0
    container_name: code-agent-traefik
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - code-agent

networks:
  code-agent:
    name: code-agent-network
