# Dynamic Traefik Configuration
# Rules and middlewares that can be updated without restart

http:
  middlewares:
    # CORS for local development
    cors-dev:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "*"
        accessControlExposeHeaders:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true

    # Security headers
    security-headers:
      headers:
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        frameDeny: true

    # Request logging
    request-logger:
      accessLog:
        bufferingSize: 100

    # Rate limiting for webhook endpoint
    webhook-ratelimit:
      rateLimit:
        burst: 50
        period: 1m

  routers:
    # Default route for health checks
    api:
      rule: "PathPrefix(`/api`)"
      service: "api@internal"
      entryPoints:
        - "traefik"
      middlewares:
        - "security-headers"

    # Root redirect to dashboard
    root:
      rule: "PathPrefix(`/`)"
      service: "dashboard@internal"
      entryPoints:
        - "traefik"
      middlewares:
        - "security-headers"

  services:
    # No additional services needed - Docker provider handles service discovery
