apiVersion: 1

datasources:
  # Prometheus - Metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://agent-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s

  # Loki - Logs  
  - name: Loki
    type: loki
    access: proxy
    url: http://agent-loki:3100
    editable: true
    jsonData:
      maxLines: 1000
